In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np 
decathlon = pd.read_csv("decathlon.csv", sep=";",
index_col = 0)
print(f"Dimensions = {decathlon.shape}")
decathlon


Dimensions = (41, 13)


100m  Longueur  Poids  Hauteur   400m  110m H  Disque  Perche  \
Sebrle       10.85      7.84  16.36     2.12  48.36   14.05   48.72    5.00   
Clay         10.44      7.96  15.23     2.06  49.19   14.13   50.11    4.90   
Karpov       10.50      7.81  15.93     2.09  46.81   13.97   51.65    4.60   
Macey        10.89      7.47  15.73     2.15  48.97   14.56   48.34    4.40   
Warners      10.62      7.74  14.48     1.97  47.97   14.01   43.73    4.90   
Zsivoczky    10.91      7.14  15.31     2.12  49.40   14.95   45.62    4.70   
Hernu        10.97      7.19  14.65     2.03  48.73   14.25   44.72    4.80   
Nool         10.80      7.53  14.26     1.88  48.81   14.80   42.05    5.40   
Bernard      10.69      7.48  14.80     2.12  49.13   14.17   44.75    4.40   
Schwarzl     10.98      7.49  14.01     1.94  49.76   14.25   42.43    5.10   
Pogorelov    10.95      7.31  15.10     2.06  50.79   14.21   44.60    5.00   
Schoenbeck   10.90      7.30  14.77     1.88  50.30   14.34   44.41    5.00   
Barras       11.14      6.99  14.91     1.94  49.41   14.37   44.83    4.60   
Smith        10.85      6.81  15.24     1.91  49.27   14.01   49.02    4.20   
Averyanov    10.55      7.34  14.44     1.94  49.72   14.39   39.88    4.80   
Ojaniemi     10.68      7.50  14.97     1.94  49.12   15.01   40.35    4.60   
Smirnov      10.89      7.07  13.88     1.94  49.11   14.77   42.47    4.70   
Qi           11.06      7.34  13.55     1.97  49.65   14.78   45.13    4.50   
Drews        10.87      7.38  13.07     1.88  48.51   14.01   40.11    5.00   
Parkhomenko  11.14      6.61  15.69     2.03  51.04   14.88   41.90    4.80   
Terek        10.92      6.94  15.15     1.94  49.56   15.12   45.62    5.30   
Gomez        11.08      7.26  14.57     1.85  48.61   14.41   40.95    4.40   
Turi         11.08      6.91  13.62     2.03  51.67   14.26   39.83    4.80   
Lorenzo      11.10      7.03  13.22     1.85  49.34   15.38   40.22    4.50   
Karlivans    11.33      7.26  13.30     1.97  50.54   14.98   43.34    4.50   
Korkizoglou  10.86      7.07  14.81     1.94  51.16   14.96   46.07    4.70   
Uldal        11.23      6.99  13.53     1.85  50.95   15.09   43.01    4.50   
Casarsa      11.36      6.68  14.92     1.94  53.20   15.39   48.66    4.40   
SEBRLE       11.04      7.58  14.83     2.07  49.81   14.69   43.75    5.02   
CLAY         10.76      7.40  14.26     1.86  49.37   14.05   50.72    4.92   
KARPOV       11.02      7.30  14.77     2.04  48.37   14.09   48.95    4.92   
BERNARD      11.02      7.23  14.25     1.92  48.93   14.99   40.87    5.32   
YURKOV       11.34      7.09  15.19     2.10  50.42   15.31   46.26    4.72   
WARNERS      11.11      7.60  14.31     1.98  48.68   14.23   41.10    4.92   
ZSIVOCZKY    11.13      7.30  13.48     2.01  48.62   14.17   45.67    4.42   
McMULLEN     10.83      7.31  13.76     2.13  49.91   14.38   44.41    4.42   
MARTINEAU    11.64      6.81  14.57     1.95  50.14   14.93   47.60    4.92   
HERNU        11.37      7.56  14.41     1.86  51.10   15.06   44.99    4.82   
BARRAS       11.33      6.97  14.09     1.95  49.48   14.48   42.10    4.72   
NOOL         11.33      7.27  12.68     1.98  49.20   15.29   37.92    4.62   
BOURGUIGNON  11.36      6.80  13.46     1.86  51.16   15.67   40.49    5.02   

             Javelot   1500m  Classement  Points Competition  
Sebrle         70.52  280.01           1    8893          JO  
Clay           69.71  282.00           2    8820          JO  
Karpov         55.54  278.11           3    8725          JO  
Macey          58.46  265.42           4    8414          JO  
Warners        55.39  278.05           5    8343          JO  
Zsivoczky      63.45  269.54           6    8287          JO  
Hernu          57.76  264.35           7    8237          JO  
Nool           61.33  276.33           8    8235          JO  
Bernard        55.27  276.31           9    8225          JO  
Schwarzl       56.32  273.56          10    8102          JO  
Po

In [45]:
decathlon.shape

(41, 13)

In [40]:
X = decathlon.iloc[:,0:10]
X

100m  Longueur  Poids  Hauteur   400m  110m H  Disque  Perche  \
Sebrle       10.85      7.84  16.36     2.12  48.36   14.05   48.72    5.00   
Clay         10.44      7.96  15.23     2.06  49.19   14.13   50.11    4.90   
Karpov       10.50      7.81  15.93     2.09  46.81   13.97   51.65    4.60   
Macey        10.89      7.47  15.73     2.15  48.97   14.56   48.34    4.40   
Warners      10.62      7.74  14.48     1.97  47.97   14.01   43.73    4.90   
Zsivoczky    10.91      7.14  15.31     2.12  49.40   14.95   45.62    4.70   
Hernu        10.97      7.19  14.65     2.03  48.73   14.25   44.72    4.80   
Nool         10.80      7.53  14.26     1.88  48.81   14.80   42.05    5.40   
Bernard      10.69      7.48  14.80     2.12  49.13   14.17   44.75    4.40   
Schwarzl     10.98      7.49  14.01     1.94  49.76   14.25   42.43    5.10   
Pogorelov    10.95      7.31  15.10     2.06  50.79   14.21   44.60    5.00   
Schoenbeck   10.90      7.30  14.77     1.88  50.30   14.34   44.41    5.00   
Barras       11.14      6.99  14.91     1.94  49.41   14.37   44.83    4.60   
Smith        10.85      6.81  15.24     1.91  49.27   14.01   49.02    4.20   
Averyanov    10.55      7.34  14.44     1.94  49.72   14.39   39.88    4.80   
Ojaniemi     10.68      7.50  14.97     1.94  49.12   15.01   40.35    4.60   
Smirnov      10.89      7.07  13.88     1.94  49.11   14.77   42.47    4.70   
Qi           11.06      7.34  13.55     1.97  49.65   14.78   45.13    4.50   
Drews        10.87      7.38  13.07     1.88  48.51   14.01   40.11    5.00   
Parkhomenko  11.14      6.61  15.69     2.03  51.04   14.88   41.90    4.80   
Terek        10.92      6.94  15.15     1.94  49.56   15.12   45.62    5.30   
Gomez        11.08      7.26  14.57     1.85  48.61   14.41   40.95    4.40   
Turi         11.08      6.91  13.62     2.03  51.67   14.26   39.83    4.80   
Lorenzo      11.10      7.03  13.22     1.85  49.34   15.38   40.22    4.50   
Karlivans    11.33      7.26  13.30     1.97  50.54   14.98   43.34    4.50   
Korkizoglou  10.86      7.07  14.81     1.94  51.16   14.96   46.07    4.70   
Uldal        11.23      6.99  13.53     1.85  50.95   15.09   43.01    4.50   
Casarsa      11.36      6.68  14.92     1.94  53.20   15.39   48.66    4.40   
SEBRLE       11.04      7.58  14.83     2.07  49.81   14.69   43.75    5.02   
CLAY         10.76      7.40  14.26     1.86  49.37   14.05   50.72    4.92   
KARPOV       11.02      7.30  14.77     2.04  48.37   14.09   48.95    4.92   
BERNARD      11.02      7.23  14.25     1.92  48.93   14.99   40.87    5.32   
YURKOV       11.34      7.09  15.19     2.10  50.42   15.31   46.26    4.72   
WARNERS      11.11      7.60  14.31     1.98  48.68   14.23   41.10    4.92   
ZSIVOCZKY    11.13      7.30  13.48     2.01  48.62   14.17   45.67    4.42   
McMULLEN     10.83      7.31  13.76     2.13  49.91   14.38   44.41    4.42   
MARTINEAU    11.64      6.81  14.57     1.95  50.14   14.93   47.60    4.92   
HERNU        11.37      7.56  14.41     1.86  51.10   15.06   44.99    4.82   
BARRAS       11.33      6.97  14.09     1.95  49.48   14.48   42.10    4.72   
NOOL         11.33      7.27  12.68     1.98  49.20   15.29   37.92    4.62   
BOURGUIGNON  11.36      6.80  13.46     1.86  51.16   15.67   40.49    5.02   

             Javelot   1500m  
Sebrle         70.52  280.01  
Clay           69.71  282.00  
Karpov         55.54  278.11  
Macey          58.46  265.42  
Warners        55.39  278.05  
Zsivoczky      63.45  269.54  
Hernu          57.76  264.35  
Nool           61.33  276.33  
Bernard        55.27  276.31  
Schwarzl       56.32  273.56  
Pogorelov      53.45  287.63  
Schoenbeck     60.89  278.82  
Barras         64.55  267.09  
Smith          61.52  272.74  
Averyanov      54.51  271.02  
Ojaniemi       59.26  275.71  
Smirnov        60.88  263.31  
Qi             60.79  272.63  
Drews          51.53  274.21  
Parkhomenko    65.82  277.94  
Terek          50.62  290.36  
Gomez        

In [37]:
help(decathlon.iloc)

Help on _iLocIndexer in module pandas.core.indexing object:

class _iLocIndexer(_LocationIndexer)
 |  Purely integer-location based indexing for selection by position.
 |  
 |  ``.iloc[]`` is primarily integer position based (from ``0`` to
 |  ``length-1`` of the axis), but may also be used with a boolean
 |  array.
 |  
 |  Allowed inputs are:
 |  
 |  - An integer, e.g. ``5``.
 |  - A list or array of integers, e.g. ``[4, 3, 0]``.
 |  - A slice object with ints, e.g. ``1:7``.
 |  - A boolean array.
 |  - A ``callable`` function with one argument (the calling Series, DataFrame
 |    or Panel) and that returns valid output for indexing (one of the above)
 |  
 |  ``.iloc`` will raise ``IndexError`` if a requested indexer is
 |  out-of-bounds, except *slice* indexers which allow out-of-bounds
 |  indexing (this conforms with python/numpy *slice* semantics).
 |  
 |  See more at :ref:`Selection by Position <indexing.integer>`
 |  
 |  Method resolution order:
 |      _iLocIndexer
 |     

In [47]:
help(StandardScaler)

Help on class StandardScaler in module sklearn.preprocessing.data:

class StandardScaler(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  StandardScaler(copy=True, with_mean=True, with_std=True)
 |  
 |  Standardize features by removing the mean and scaling to unit variance
 |  
 |  Centering and scaling happen independently on each feature by computing
 |  the relevant statistics on the samples in the training set. Mean and
 |  standard deviation are then stored to be used on later data using the
 |  `transform` method.
 |  
 |  Standardization of a dataset is a common requirement for many
 |  machine learning estimators: they might behave badly if the
 |  individual feature do not more or less look like standard normally
 |  distributed data (e.g. Gaussian with 0 mean and unit variance).
 |  
 |  For instance many elements used in the objective function of
 |  a learning algorithm (such as the RBF kernel of Support Vector
 |  Machines or the L1 and L2 regularizers of li

In [73]:
scaler = StandardScaler(with_mean = True)
Y = scaler.fit_transform(X)

In [ ]:
Y.mean_()

In [74]:
help(Y.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [77]:
Y.mean(axis = 0)

array([ 6.66675387e-15, -2.33417621e-15, -1.51640218e-15, -1.67887384e-16,
       -7.27331474e-15, -2.80534403e-15, -7.41953924e-16, -8.85470559e-16,
        2.12025519e-15, -2.87574842e-15])

In [80]:
# matrice des variances des differentes colonnes 
S= Y.var(axis = 0)
S


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
n = X.shape[0]
D = np.diag(np.ones(n)) 
D = D/n
D

array([[0.02439024, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02439024, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02439024, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.02439024, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.02439024,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02439024]])

In [88]:
M = np.diag(1/np.sqrt(S))
M

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [91]:
V=Y.T.dot(D).dot(Y)
V

array([[ 1.        , -0.59867767, -0.35648227, -0.24625292,  0.52029815,
         0.57988893, -0.22170757, -0.08253683, -0.15774645, -0.06054645],
       [-0.59867767,  1.        ,  0.18330436,  0.29464444, -0.60206262,
        -0.50541009,  0.19431009,  0.20401411,  0.11975893, -0.03368613],
       [-0.35648227,  0.18330436,  1.        ,  0.48921153, -0.13843292,
        -0.25161571,  0.6157681 ,  0.06118185,  0.37495551,  0.11580306],
       [-0.24625292,  0.29464444,  0.48921153,  1.        , -0.18795693,
        -0.28328909,  0.36921834, -0.15618074,  0.17188009, -0.04490252],
       [ 0.52029815, -0.60206262, -0.13843292, -0.18795693,  1.        ,
         0.54798776, -0.11787936, -0.07929247,  0.0042321 ,  0.40810643],
       [ 0.57988893, -0.50541009, -0.25161571, -0.28328909,  0.54798776,
         1.        , -0.32620096, -0.00270388,  0.00874325,  0.03754024],
       [-0.22170757,  0.19431009,  0.6157681 ,  0.36921834, -0.11787936,
        -0.32620096,  1.        , -0.1500724 

In [95]:
VM = V.dot(M)
VM

array([[ 1.        , -0.59867767, -0.35648227, -0.24625292,  0.52029815,
         0.57988893, -0.22170757, -0.08253683, -0.15774645, -0.06054645],
       [-0.59867767,  1.        ,  0.18330436,  0.29464444, -0.60206262,
        -0.50541009,  0.19431009,  0.20401411,  0.11975893, -0.03368613],
       [-0.35648227,  0.18330436,  1.        ,  0.48921153, -0.13843292,
        -0.25161571,  0.6157681 ,  0.06118185,  0.37495551,  0.11580306],
       [-0.24625292,  0.29464444,  0.48921153,  1.        , -0.18795693,
        -0.28328909,  0.36921834, -0.15618074,  0.17188009, -0.04490252],
       [ 0.52029815, -0.60206262, -0.13843292, -0.18795693,  1.        ,
         0.54798776, -0.11787936, -0.07929247,  0.0042321 ,  0.40810643],
       [ 0.57988893, -0.50541009, -0.25161571, -0.28328909,  0.54798776,
         1.        , -0.32620096, -0.00270388,  0.00874325,  0.03754024],
       [-0.22170757,  0.19431009,  0.6157681 ,  0.36921834, -0.11787936,
        -0.32620096,  1.        , -0.1500724 

In [2]:
# TROUVER LES VALEURS PROPRES ET LES VECTEURS PROPRES DE VM et normalisez les vecteurs propres 


In [10]:
import matplotlib.pyplot as plt 

## Ma class ACP 
class MyACP : 
     
      def __init__(self, X: pd.DataFrame, D : np.array = None , M : np.array = None ) :  
        dim = X.shape
        n = dim[0]
        p = dim[1]
        
        #Données centrées
        self.Y = StandardScaler(with_mean = True , with_std = False).fit_transform(X)
        
        #matrice des poids 
        if D is None : 
            self.D = np.diag((1/n)*np.ones(n))
        else :
            self.D = D.copy()
            
        
        #Variances covariances 
        self.V = Y.dot(D).dot(Y)
        
        #Metrique
        
        if M is not None :
            self.M = M.copy()
        else : 
            self.M= np.diag(1/n.diag(self.V))
        
        #VM 
        VM = self.V.dot(self.M)
        
        #Decomposition spectrale 
        val_propres , vect_propres = np.linalg.eig(VM)
            
acp = MyACP()


constructeur
